// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDhZxOEQX0sRYjlxlfS9DRbQc4x6ZmcAM',
    appId: '1:1044190581234:web:44c6c665628aeeca7f5b6b',
    messagingSenderId: '1044190581234',
    projectId: 'staff-tracker-a09d3',
    authDomain: 'staff-tracker-a09d3.firebaseapp.com',
    storageBucket: 'staff-tracker-a09d3.firebasestorage.app',
    measurementId: 'G-LWQDDPV13C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPBUCIBDGgVBQ7e6FN3b3de73pEwBGCuE',
    appId: '1:1044190581234:android:2c7a672050a156ce7f5b6b',
    messagingSenderId: '1044190581234',
    projectId: 'staff-tracker-a09d3',
    storageBucket: 'staff-tracker-a09d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAqTi25QbFdSlJcYopaV6m1qVGMl1ZszE',
    appId: '1:1044190581234:ios:4497f07a1cd0086b7f5b6b',
    messagingSenderId: '1044190581234',
    projectId: 'staff-tracker-a09d3',
    storageBucket: 'staff-tracker-a09d3.firebasestorage.app',
    iosBundleId: 'com.example.staffTracking',
  );
}
